### ISSUE TITLE
You must define a type

### ISSUE THREAD

**Issue by victorgp89** [goetas-webservices/soap-server#1]
Hello, 

I have this in my config.yml:
```yml
soap_client: ~
xsd2php:
  namespaces:
    'http://www.example.org/test/': 'Test'
  destinations_php:
   'Test' : src
  destinations_jms:
    'TestNs/MyApp': metadata/Test
wsdl2php:
  metadata:
    '/var/www/synergy-generator/include/XSD/test.wsdl': ~**

```
In my class also have this: 

```php
/**
 * Class representing GetSimpleInput
 */
class GetSimpleInput
{

    /**
     * @property \Test\SoapEnvelope\Parts\GetSimpleInput $body
     */
    private $body = null;

    /**
     * @property mixed $header
     */
    private $header = null;

    /**
     * Gets as body
     *
     * @return \Test\SoapEnvelope\Parts\GetSimpleInput
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * Sets a new body
     *
     * @param \Test\SoapEnvelope\Parts\GetSimpleInput $body
     * @return self
     */
    public function setBody(\Test\SoapEnvelope\Parts\GetSimpleInput $body)
    {
        $this->body = $body;
        return $this;
    }

    /**
     * Gets as header
     *
     * @return mixed
     */
    public function getHeader()
    {
        return $this->header;
    }

    /**
     * Sets a new header
     *
     * @param $header
     * @return self
     */
    public function setHeader($header)
    {
        $this->header = $header;
        return $this;
    }


}

```
But when I deseralize the object this return: 

**You must define a type for Igm\SoapServices\SoapEnvelope\Messages\GetSimpleInput::$body.**
